services:
  express-server:
    image: node-docker
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./index.js
        target: /app/index.js
    command: npx nodemon -L index.js